services:
  postgres_ha_principal:
    image: bitnami/postgresql:latest
    container_name: postgres_ha_principal
    restart: unless-stopped
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicador
      - POSTGRESQL_REPLICATION_PASSWORD=replica123
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_DATABASE=consultorio_dental
    ports:
      - "5444:5432"
    volumes:
      - postgres_ha_principal_data:/bitnami/postgresql
    networks:
      - consultorio_ha
    healthcheck:
      test: ["CMD", "/opt/bitnami/postgresql/bin/pg_isready", "-h", "127.0.0.1", "-p", "5432", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  postgres_ha_replica:
    image: bitnami/postgresql:latest
    container_name: postgres_ha_replica
    restart: unless-stopped
    depends_on:
      - postgres_ha_principal
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicador
      - POSTGRESQL_REPLICATION_PASSWORD=replica123
      - POSTGRESQL_MASTER_HOST=postgres_ha_principal
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_DATABASE=consultorio_dental
    ports:
      - "5443:5432"
    volumes:
      - postgres_ha_replica_data:/bitnami/postgresql
    networks:
      - consultorio_ha
    healthcheck:
      test: ["CMD", "/opt/bitnami/postgresql/bin/pg_isready", "-h", "127.0.0.1", "-p", "5432", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  postgres_ha_principal_data:
  postgres_ha_replica_data:

networks:
  consultorio_ha:
